[programs.localnet]
best_apy = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 20_000

[test.validator]
url = "https://api.mainnet-beta.solana.com"


# mango
[[test.validator.clone]]
address = "mv3ekLzLbnVPNxjSKvqBpU3ZeZXPQdEC3bp5MDEBG68"

[[test.validator.clone]]
address = "EBDRoayCDDUvDgCimta45ajQeXbexv7aKqJubruqpyvu"

[[test.validator.clone]]
address = "98pjRuQjK3qA6gXts96PqZT4Ze5QmnCmt3QYjhbUSPue"

[[test.validator.clone]]
address = "9BVcYqEQxyccuwznvxXqDkSJFavvTyheiTYk231T1A8S"

[[test.validator.clone]]
address = "2bqJYcA1A8gw4qJFjyE2G4akiUunpd9rP6QzfnxHqSqr"

[[test.validator.clone]]
address = "7jH1uLmiB2zbHNe6juZZYjQCrvquakTwd3yMaQpeP8rR"

[[test.validator.clone]]
address = "AVn3JRGhifPCxjxZsU3tQuo4U4dTHizHzBDGW983tx47"


# port
[[test.validator.clone]]
address = "Port7uDYB3wk6GJAw4KT1WpTeMtSu9bTcChBHkX2LfR"

[[test.validator.clone]]
address = "stkarvwmSzv2BygN5e2LeTwimTczLWHCKPKGC2zVLiq"

[[test.validator.clone]]
address = "6T4XxKerq744sSuj3jaoV6QiZ8acirf4TrPwQzHAoSy5"

[[test.validator.clone]]
address = "X9ByyhmtQH3Wjku9N5obPy54DbVjZV7Z99TPJZ2rwcs"

[[test.validator.clone]]
address = "8ezDtNNhX91t1NbSLe8xV2PcCEfoQjEm2qDVGjt3rjhg"

[[test.validator.clone]]
address = "BLAFX12cDmsumyB6k3L6whJZqNqySaWeCmS5rVuzy3SS"

[[test.validator.clone]]
address = "DAkXbEKmiLtLKQWq9XNscsmjpkNsR18TfpcqnGNa9hTY"

[[test.validator.clone]]
address = "zqSd6GnFmEW6usPSR92aLHCm4JLKNGARUp8shTkyPBE"

[[test.validator.clone]]
address = "H6ARHf6YXhGYeQfUzQNGk6rDNnLBQKrenN712K4AQJEG"

[[test.validator.clone]]
address = "PoRTjZMPXb9T7dyU7tpLEZRQj7e6ssfAE62j2oQuc6y"

[[test.validator.clone]]
address = "6bUuedxRxLPjDELwt3x8enbhL1N3cJDTJQ1zxkhxd8u2"


# solend
[[test.validator.clone]]
address = "So1endDq2YkqhipRh3WViPa8hdiSpxWy6z3Z6tMCpAo"

[[test.validator.clone]]
address = "8PbodeaosQP19SjYFx855UMqWxH2HynZLdBXmsrbac36"

[[test.validator.clone]]
address = "8UviNr47S8eL6J3WfDxMRa3hvLta1VDJwNWqsDgtN3Cv"

[[test.validator.clone]]
address = "5h6ssFpeDeRbzsEHDbTQNH7nVGgsKrZydxdSTnLm6QdV"

[[test.validator.clone]]
address = "4UpD2fh7xH3VP9QQaXtsS1YY3bxzWhtfpks7FatyKvdY"

[[test.validator.clone]]
address = "B1ATuYXNkacjjJS78MAmqu8Lu8PvEPt51u4oBasH1m1g"

[[test.validator.clone]]
address = "H6ARHf6YXhGYeQfUzQNGk6rDNnLBQKrenN712K4AQJEG"

[[test.validator.clone]]
address = "AdtRGGhmqvom3Jemp5YNrxd9q9unX36BZk1pujkkXijL"


# tulip
[[test.validator.clone]]
address = "4bcFeLv4nydFrsZqV5CgwCVrPhkQKsXtzfy2KyMz7ozM"

[[test.validator.clone]]
address = "D1cqtVThyebK9KXKGXrCEuiqaNf5L4UfM1vHgCqiJxym"

[[test.validator.clone]]
address = "FzbfXR7sopQL29Ubu312tkqWMxSre4dYSrFyYAjUYiC4"

[[test.validator.clone]]
address = "CPs1jJ5XAjhcAJsmTToWksAiPEqoLwKMbb1Z83rzaaaU"

[[test.validator.clone]]
address = "DQAcms41gjYzidRooXRE9GQM1jAauPXDcEpMbVh4FEc7"

[[test.validator.clone]]
address = "H4Q3hDbuMUw8Bu72Ph8oV2xMQ7BFNbekpfQZKS2xF7jW"


# francium
[[test.validator.clone]]
address = "FC81tbGt6JWRXidaWYFXxGnTk4VgobhJHATvTRVMqgWj"

[[test.validator.clone]]
address = "3Katmm9dhvLQijAvomteYMo6rfVbY5NaCRNq9ZBqBgr6"

[[test.validator.clone]]
address = "EnZC8MB6QLTxwN1LNqCXYC7XMpvXqitnYQPf5y5AcQRn"

[[test.validator.clone]]
address = "GiJwrxQW5NQWWAva4rnDMXwHxfrhyUzwMX5to1pmCCgF"

[[test.validator.clone]]
address = "92Zst3rEoJsyZUW2yNc2811GtkBwFrm3tqgxMTtFWuSB"

[[test.validator.clone]]
address = "4XNif294wbrxj6tJ8K5Rg7SuaEACnu9s2L27i28MQB6E"

[[test.validator.clone]]
address = "G8MpQfTa18RcGK6xdKxKqG3u9NXWwqEMN3YM4MAFSukS"

[[test.validator.clone]]
address = "5Dwb6bW6nJ7tawnXXuJLRRsHnpDWrsQGMBNePsi2HHNc"

[[test.validator.clone]]
address = "CRmaS1yBemFcHAooAfRUM41ZCBpnM7FCRKi7x71YXnTj"

[[test.validator.clone]]
address = "CRmaS1yBemFcHAooAfRUM41ZCBpnM7FCRKi7x71YXnTj"

[[test.validator.clone]]
address = "Hjibp1cn2bSk1dkTdpbxez3YAiBGTLjzc8xZ8LbCCUHS"

[[test.validator.clone]]
address = "Hjibp1cn2bSk1dkTdpbxez3YAiBGTLjzc8xZ8LbCCUHS"
