[programs.localnet]
best_apy = "GGo1dnYpjKfe9omzUaFtaCyizvwpAMf3NhxSCMD61F3A"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[test]
startup_wait = 20_000

[test.validator]
url = "https://api.mainnet-beta.solana.com"
warp_slot = ""


# francium_exe
[[test.validator.clone]]
address = "FC81tbGt6JWRXidaWYFXxGnTk4VgobhJHATvTRVMqgWj"

# francium_lend_rewards_exe
[[test.validator.clone]]
address = "3Katmm9dhvLQijAvomteYMo6rfVbY5NaCRNq9ZBqBgr6"

# mango_exe
[[test.validator.clone]]
address = "mv3ekLzLbnVPNxjSKvqBpU3ZeZXPQdEC3bp5MDEBG68"

# port_exe
[[test.validator.clone]]
address = "Port7uDYB3wk6GJAw4KT1WpTeMtSu9bTcChBHkX2LfR"

# port_staking_exe
[[test.validator.clone]]
address = "stkarvwmSzv2BygN5e2LeTwimTczLWHCKPKGC2zVLiq"

# solend_exe
[[test.validator.clone]]
address = "So1endDq2YkqhipRh3WViPa8hdiSpxWy6z3Z6tMCpAo"

# tulip_exe
[[test.validator.clone]]
address = "4bcFeLv4nydFrsZqV5CgwCVrPhkQKsXtzfy2KyMz7ozM"
